#!/usr/bin/env bash
# This script will install Nginx on any server
# It get run

sudo apt-get update
sudo apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html
ufw allow 'Nginx HTTP'
service nginx start
