#!/bin/bash
# This is a Bash that configure a New Server (Load Balancer) To meet a certain requirement as written below.

# sudo apt-get update
# sudo apt-get install haproxy -y

# Configuration
FILEPATH=/etc/haproxy/haproxy.cfg

# Frontend Configuration
FRONT="
frontend yemi_web_frontend
    bind *:80
    mode http
    default_backend yemi_web_backend"

echo "$FRONT" | sudo tee -a "$FILEPATH"

# Backend Configuration
CONFIG="
backend yemi_web_backend
    balance roundrobin
    server 1302-web-01 34.224.95.198:80 check
    server 1302-web-02 52.87.220.62:80 check"

echo "$CONFIG" | sudo tee -a "$FILEPATH"

# Enabling haproxy to run on by default
echo "ENDABLE=1" | sudo tee /etc/default/haproxy

sudo systemctl restart haproxy
