#!/usr/bin/env bash
# This is a script that pings an IP address and displays the time
# It takes my device to move across the path that lead to IP Address

if [ "$1" == "" ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
