#!/usr/bin/env bash
# This script prints "Best School" 10 times using while loop
# And an If statement 
i=10
while [ $i -gt 0 ];
	do
	echo "Best School"
	if [[ $i -eq 2 ]]
	then echo "Hi"
	fi
	i=$((i-1))
done
