#!/usr/bin/env bash
# This script changes the IP Address of:
# localhost to 127.0.0.2 and
# facebook.com to 8.8.8.8 when run with the ping command.
cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
