#!/usr/bin/env bash
# Creating a bash script that that uses ssh to connect
# to your server using the private key ~/.ssh/school
# with the user ubuntu.

# Server to connect to

server_ip=8.8.8.8

username=ubuntu

private_key=~/.ssh/school

ssh-add $private_key

ssh $username@$server_id
